# Copyright 2019 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was mostly generated by the IBM Watson Machine Learning service. It was slightly
# modified and serves as a quick way to test the credentials and model.
# To run this script update the credentials below, the values to be scored, and
# run it with `python predict.py` to see the results.

import json
import requests

# retrieve your wml_service_credentials_url from the service credentials associated
# with your IBM Cloud Watson Machine Learning service instance
wml_instance = '***'
wml_deployment = '***'
wml_service_credentials_url = 'https://us-south.ml.cloud.ibm.com'
wml_service_api_key = '***'
iam_url = "https://iam.cloud.ibm.com/identity/token"

# Get an IAM token from IBM Cloud
headers = { "Content-Type" : "application/x-www-form-urlencoded",
            "Accept": "application/json" }
data    = "apikey=" + wml_service_api_key + "&grant_type=urn:ibm:params:oauth:grant-type:apikey"
IBM_cloud_IAM_uid = "bx"
IBM_cloud_IAM_pwd = "bx"
response  = requests.post(iam_url, headers=headers, data=data, auth=( IBM_cloud_IAM_uid, IBM_cloud_IAM_pwd ) )
iam_token = response.json()["access_token"]

# Now to call the WML service
header = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + iam_token, 'ML-Instance-ID': wml_instance}
# NOTE: manually define and pass the array(s) of values to be scored in the next line
array_of_values_to_be_scored = [33, 20, 200, 20, 33, 'M', 'N', 'N', 125]
payload_scoring = {"fields": ["AVGHEARTBEATSPERMIN", "PALPITATIONSPERDAY", "CHOLESTEROL", "BMI", "AGE", "SEX", "FAMILYHISTORY", "SMOKERLAST5YRS", "EXERCISEMINPERWEEK"], "values": [array_of_values_to_be_scored]}
scoring_url = '{url}/v3/wml_instances/{instance}/deployments/{deployment}/online'.format(url=wml_service_credentials_url, instance=wml_instance, deployment=wml_deployment)
response_scoring = requests.post(scoring_url, json=payload_scoring, headers=header)

# Print the output
print("Scoring response")
parsed = json.loads(response_scoring.text)
values = parsed['values']
print(values)

# Format the output
prediction = 'Y' if values[0][17] == 1.0 else 'N'
confidence = str(round(values[0][16][1] * 100, 2)) + '%' if values[0][17] == 1.0 else str(round(values[0][16][0] * 100, 2)) + '%'
print("Heart Risk Prediction (Y/N): {}\nModel Confidence: {}".format(prediction, confidence))
